name: Next.js CI

on: [push, pull_request]
jobs:
  node:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # installing Node
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          # this will use the latest Node 18 version
          node-version: 18.x
      # install dependencies using clean install to avoid package lock updates
      - run: npm install --legacy-peer-deps
      - run: npm run build
      - run: npm run format
